'use client';
import {useQuery,useMutation} from '@tanstack/react-query';
import {apiService} from './apiService';
import {useCodeForgeStore} from './useStore';
export const useCurrentUser=()=>useQuery({queryKey:['codeforge-user'],queryFn:apiService.getCurrentUser});
export const useProblems=(filters?:Record<string,unknown>)=>useQuery({queryKey:['codeforge-problems',filters],queryFn:()=>apiService.getProblems(filters)});
export const useProblem=(id:string)=>useQuery({queryKey:['codeforge-problem',id],queryFn:()=>apiService.getProblemById(id),enabled:!!id});
export const useGlobalLeaderboard=(timeframe:'Overall'|'Weekly'|'Monthly'='Overall')=>useQuery({queryKey:['codeforge-leaderboard',timeframe],queryFn:()=>apiService.getGlobalLeaderboard(timeframe)});
export const useSubmitCode=()=>{const add=useCodeForgeStore(s=>s.addSubmission);return useMutation({mutationFn:(p:{problemId:string;code:string;language:string})=>apiService.submitCode(p.problemId,p.code,p.language),onSuccess:add})};
export const useRunCode=()=>useMutation({mutationFn:(p:{problemId:string;code:string;language:string})=>apiService.runCode(p.problemId,p.code,p.language)});
export const useSubmission=(id:string)=>useQuery({queryKey:['codeforge-submission',id],queryFn:()=>apiService.getSubmission(id),enabled:!!id});
export const useAskAI=()=>useMutation({mutationFn:apiService.askAI});
