import type { Difficulty, SubmissionStatus } from './types';
export const formatNumber=(n:number)=>new Intl.NumberFormat('en-US').format(n);
export const formatAcceptance=(n:number)=>`${n.toFixed(1)}%`;
export const formatDate=(d:Date|string)=>new Date(d).toLocaleDateString();
export const formatDateTime=(d:Date|string)=>new Date(d).toLocaleString();
export const formatTime=(ms:number)=>ms<1000?`${ms}ms`:`${(ms/1000).toFixed(2)}s`;
export const formatMemory=(mb:number)=>`${mb.toFixed(1)} MB`;
export const getDifficultyColor=(d:Difficulty)=>({EASY:'text-emerald-400',MEDIUM:'text-yellow-400',HARD:'text-red-400'}[d]);
export const getDifficultyBgColor=(d:Difficulty)=>({EASY:'bg-emerald-500/10',MEDIUM:'bg-yellow-500/10',HARD:'bg-red-500/10'}[d]);
export const getStatusColor=(s:SubmissionStatus)=>s==='ACCEPTED'?'text-emerald-400':s==='RUNTIME_ERROR'||s==='TIME_LIMIT_EXCEEDED'?'text-orange-400':'text-red-400';
export const truncate=(s:string,n:number)=>s.length>n?`${s.slice(0,n-1)}…`:s;
export const capitalize=(s:string)=>s.charAt(0).toUpperCase()+s.slice(1);
export const slugify=(s:string)=>s.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
export const debounce=<T extends (...a:any[])=>void>(fn:T,wait:number)=>{let t:ReturnType<typeof setTimeout>;return((...a:Parameters<T>)=>{clearTimeout(t);t=setTimeout(()=>fn(...a),wait);}) as T};
export const copyToClipboard=async(s:string)=>{try{await navigator.clipboard.writeText(s);return true}catch{return false}};
export const groupBy=<T,K extends PropertyKey>(items:T[],key:(x:T)=>K)=>items.reduce((a,x)=>{const k=key(x);(a[k]??=[]).push(x);return a},{ } as Record<K,T[]>);
